---
- name: Установить зависимости для apt
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - software-properties-common
      - curl
    state: present
    update_cache: yes

- name: Скопировать локальный пакет Kibana на сервер
  ansible.builtin.copy:
    src: kibana-9.2.0-amd64.deb
    dest: /tmp/kibana-9.2.0-amd64.deb
    mode: '0644'

- name: Установить Kibana через dpkg
  ansible.builtin.apt:
    deb: /tmp/kibana-9.2.0-amd64.deb
    state: present

- name: Создать пользователя Kibana
  ansible.builtin.user:
    name: kibana
    shell: /sbin/nologin
    system: yes
    create_home: no

- name: Создать директории для Kibana
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: kibana
    group: kibana
    mode: '0755'
  loop:
    - /etc/kibana
    - /var/lib/kibana
    - /var/log/kibana

- name: Скопировать конфигурационный файл kibana.yml
  ansible.builtin.template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: kibana
    group: kibana
    mode: '0644'
  notify: Restart Kibana

- name: Включить и запустить сервис Kibana
  ansible.builtin.service:
    name: kibana
    state: started
    enabled: yes
