global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'elastic'
    static_configs:
      - targets: ['elastic:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9100']

  - job_name: 'kibana'
    static_configs:
      - targets: ['kibana:9100']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:9100']

  - job_name: 'web_a'
    static_configs:
      - targets: ['web_a:9100']

  - job_name: 'web_b'
    static_configs:
      - targets: ['web_b:9100']