global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'bastion'
    static_configs:
      - targets: ['bastion:9100']

  - job_name: 'elastic'
    static_configs:
      - targets: ['elastic:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9100']

  - job_name: 'kibana'
    static_configs:
      - targets: ['kibana:9100']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:9100']

  - job_name: 'web-a'
    static_configs:
      - targets: ['web-a:9100']

  - job_name: 'web-b'
    static_configs:
      - targets: ['web-b:9100']
